"""other 2

Revision ID: c7c9e94acecd
Revises: de92b4238da0
Create Date: 2023-05-26 08:57:17.649806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c9e94acecd'
down_revision = 'de92b4238da0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_b', sa.Column('other_2', sa.String(length=100), nullable=False), schema='app_b')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_b', 'other_2', schema='app_b')
    # ### end Alembic commands ###
