"""Add a column

Revision ID: de92b4238da0
Revises: 9d109b9ca4a1
Create Date: 2023-05-25 19:40:31.330135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de92b4238da0'
down_revision = '9d109b9ca4a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_b', sa.Column('other', sa.String(length=100), nullable=False), schema='app_b')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_b', 'other', schema='app_b')
    # ### end Alembic commands ###
