version: "3.9"
services:
  auth:
    image: separable-mgrations/auth:local
    restart: unless-stopped
    build:
      context: ./auth
      dockerfile: Dockerfile
    volumes:
      - "./auth:/app"
    depends_on:
      - db
    environment:
      DB_CONNECTION_STRING: "postgresql://postgres:postgres@db:5432/test_db"
      DB_SCHEMA: "auth"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

  billing:
    image: separable-mgrations/billing:local
    restart: unless-stopped
    build:
      context: ./billing
      dockerfile: Dockerfile
    volumes:
      - "./billing:/app"
      # In order to reference models from auth
      - "./auth:/app/auth"
    depends_on:
      - db
    environment:
      DB_CONNECTION_STRING: "postgresql://postgres:postgres@db:5432/test_db"
      DB_SCHEMA: "billing"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  pg_data:
