"""add user subscription table

Revision ID: cbe514674831
Revises: d9c9f79e2213
Create Date: 2023-05-26 15:24:51.314452

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cbe514674831"
down_revision = "d9c9f79e2213"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_subscription",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("subscription_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["billing.subscription.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="billing",
    )
    op.create_index(
        op.f("ix_billing_user_subscription_subscription_id"),
        "user_subscription",
        ["subscription_id"],
        unique=False,
        schema="billing",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_billing_user_subscription_subscription_id"),
        table_name="user_subscription",
        schema="billing",
    )
    op.drop_table("user_subscription", schema="billing")
    # ### end Alembic commands ###
